### ISSUE TITLE
No frametitle on first frame in appendix

### ISSUE THREAD

**Issue by AxelDuerrbaum** [jlelong/appendixnumberbeamer#3]
Hello,

with MikTeX  23.10.12, the first slide in the appendix does not have a frametitle.

pdfTeX, Version 3.141592653-2.6-1.40.25 (MiKTeX 23.10.12) (preloaded format=pdflatex 2023.10.25)  29 OCT 2023 18:28
LaTeX2e <2023-06-01> patch level 1
L3 programming layer <2023-10-10>
Document Class: beamer 2023/05/15 v3.70 A class for typesetting presentations

**Comment by jlelong** [comment]
Unfortunately, I do not have access to a MikTeX distribution butI doubt your issue is related to `appendixnumberbeamer` as it only modifies the value of `\inserttotalframenumber` and does not change the frame title.
